# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(840, 587)
        self.myfolder_tab_2 = QtWidgets.QTabWidget(MainWindow)
        self.myfolder_tab_2.setGeometry(QtCore.QRect(0, 0, 831, 581))
        self.myfolder_tab_2.setObjectName("myfolder_tab_2")
        self.myfolder_tab = QtWidgets.QWidget()
        self.myfolder_tab.setObjectName("myfolder_tab")
        self.upload_files_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.upload_files_button.setGeometry(QtCore.QRect(700, 20, 81, 23))
        self.upload_files_button.setObjectName("upload_files_button")
        self.share_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.share_button.setGeometry(QtCore.QRect(700, 180, 81, 23))
        self.share_button.setObjectName("share_button")
        self.upload_folders_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.upload_folders_button.setGeometry(QtCore.QRect(700, 60, 81, 23))
        self.upload_folders_button.setObjectName("upload_folders_button")
        self.actions_on_item = QtWidgets.QGroupBox(self.myfolder_tab)
        self.actions_on_item.setGeometry(QtCore.QRect(679, 240, 121, 171))
        font = QtGui.QFont()
        font.setBold(False)
        font.setUnderline(False)
        font.setWeight(50)
        self.actions_on_item.setFont(font)
        self.actions_on_item.setFlat(False)
        self.actions_on_item.setObjectName("actions_on_item")
        self.open_button = QtWidgets.QPushButton(self.actions_on_item)
        self.open_button.setGeometry(QtCore.QRect(20, 30, 81, 23))
        self.open_button.setObjectName("open_button")
        self.delete_button = QtWidgets.QPushButton(self.actions_on_item)
        self.delete_button.setGeometry(QtCore.QRect(20, 70, 81, 23))
        self.delete_button.setObjectName("delete_button")
        self.rename_button = QtWidgets.QPushButton(self.actions_on_item)
        self.rename_button.setGeometry(QtCore.QRect(20, 110, 81, 23))
        self.rename_button.setObjectName("rename_button")
        self.tree_view = QtWidgets.QTreeView(self.myfolder_tab)
        self.tree_view.setGeometry(QtCore.QRect(10, 10, 641, 541))
        self.tree_view.setAnimated(False)
        self.tree_view.setObjectName("tree_view")
        self.create_folder_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.create_folder_button.setGeometry(QtCore.QRect(700, 140, 81, 23))
        self.create_folder_button.setObjectName("create_folder_button")
        self.create_file_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.create_file_button.setGeometry(QtCore.QRect(700, 100, 81, 23))
        self.create_file_button.setObjectName("create_file_button")
        self.myfolder_tab_2.addTab(self.myfolder_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.myfolder_tab_2.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.myfolder_tab_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.upload_files_button.setText(_translate("MainWindow", "Upload Files"))
        self.share_button.setText(_translate("MainWindow", "Share"))
        self.upload_folders_button.setText(_translate("MainWindow", "Upload Folders"))
        self.actions_on_item.setTitle(_translate("MainWindow", "Actions On Item"))
        self.open_button.setText(_translate("MainWindow", "Open"))
        self.delete_button.setText(_translate("MainWindow", "Delete"))
        self.rename_button.setText(_translate("MainWindow", "Rename"))
        self.create_folder_button.setText(_translate("MainWindow", "Create Folder"))
        self.create_file_button.setText(_translate("MainWindow", "Create File"))
        self.myfolder_tab_2.setTabText(self.myfolder_tab_2.indexOf(self.myfolder_tab), _translate("MainWindow", "My Folder"))
        self.myfolder_tab_2.setTabText(self.myfolder_tab_2.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
