# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(836, 587)
        self.myfolder_tab_2 = QtWidgets.QTabWidget(MainWindow)
        self.myfolder_tab_2.setGeometry(QtCore.QRect(0, 0, 841, 591))
        self.myfolder_tab_2.setObjectName("myfolder_tab_2")
        self.myfolder_tab = QtWidgets.QWidget()
        self.myfolder_tab.setObjectName("myfolder_tab")
        self.upload_files_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.upload_files_button.setGeometry(QtCore.QRect(730, 80, 81, 23))
        self.upload_files_button.setObjectName("upload_files_button")
        self.share_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.share_button.setGeometry(QtCore.QRect(730, 240, 81, 23))
        self.share_button.setObjectName("share_button")
        self.upload_folders_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.upload_folders_button.setGeometry(QtCore.QRect(730, 120, 81, 23))
        self.upload_folders_button.setObjectName("upload_folders_button")
        self.create_folder_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.create_folder_button.setGeometry(QtCore.QRect(730, 200, 81, 23))
        self.create_folder_button.setObjectName("create_folder_button")
        self.create_file_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.create_file_button.setGeometry(QtCore.QRect(730, 160, 81, 23))
        self.create_file_button.setObjectName("create_file_button")
        self.go_back_button = QtWidgets.QPushButton(self.myfolder_tab)
        self.go_back_button.setGeometry(QtCore.QRect(5, 10, 61, 23))
        self.go_back_button.setObjectName("go_back_button")
        self.list_view = QtWidgets.QListView(self.myfolder_tab)
        self.list_view.setGeometry(QtCore.QRect(70, 10, 641, 541))
        self.list_view.setAcceptDrops(True)
        self.list_view.setDragEnabled(False)
        self.list_view.setSelectionMode(QtWidgets.QAbstractItemView.ExtendedSelection)
        self.list_view.setViewMode(QtWidgets.QListView.IconMode)
        self.list_view.setObjectName("list_view")
        self.myfolder_tab_2.addTab(self.myfolder_tab, "")
        self.tab_2 = QtWidgets.QWidget()
        self.tab_2.setObjectName("tab_2")
        self.myfolder_tab_2.addTab(self.tab_2, "")

        self.retranslateUi(MainWindow)
        self.myfolder_tab_2.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.upload_files_button.setText(_translate("MainWindow", "Upload Files"))
        self.share_button.setText(_translate("MainWindow", "Share"))
        self.upload_folders_button.setText(_translate("MainWindow", "Upload Folders"))
        self.create_folder_button.setText(_translate("MainWindow", "Create Folder"))
        self.create_file_button.setText(_translate("MainWindow", "Create File"))
        self.go_back_button.setText(_translate("MainWindow", "Back"))
        self.myfolder_tab_2.setTabText(self.myfolder_tab_2.indexOf(self.myfolder_tab), _translate("MainWindow", "My Folder"))
        self.myfolder_tab_2.setTabText(self.myfolder_tab_2.indexOf(self.tab_2), _translate("MainWindow", "Tab 2"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QWidget()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
