# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'SignupScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QMainWindow, QWidget, QLabel


class Ui_MainWindow(QMainWindow):
        def __init__(self):
            super().__init__()
            self.setWindowTitle("FileSpace")
            self.resize(460, 600)
            self.setMouseTracking(True)
            self.setTabletTracking(True)
            central_widget = QWidget()
            self.setCentralWidget(central_widget)
            self.label = QLabel(central_widget)
            self.label.setGeometry(QtCore.QRect(134, 60, 191, 51))
            font = QtGui.QFont()
            font.setPointSize(30)
            font.setBold(True)
            font.setItalic(False)
            font.setWeight(75)
            self.label.setFont(font)
            self.label.setMouseTracking(False)
            self.label.setObjectName("label")
            self.username_label = QtWidgets.QLabel(central_widget)
            self.username_label.setGeometry(QtCore.QRect(50, 150, 101, 23))
            font = QtGui.QFont()
            font.setPointSize(16)
            self.username_label.setFont(font)
            self.username_label.setObjectName("username_label")
            self.username_input = QtWidgets.QLineEdit(central_widget)
            self.username_input.setGeometry(QtCore.QRect(180, 150, 230, 31))
            self.username_input.setObjectName("username_input")
            self.password_input = QtWidgets.QLineEdit(central_widget)
            self.password_input.setGeometry(QtCore.QRect(209, 210, 201, 31))
            self.password_input.setTabletTracking(False)
            self.password_input.setAutoFillBackground(False)
            self.password_input.setEchoMode(QtWidgets.QLineEdit.Password)
            self.password_input.setClearButtonEnabled(False)
            self.password_input.setObjectName("password_input")
            self.password_label = QtWidgets.QLabel(central_widget)
            self.password_label.setGeometry(QtCore.QRect(20, 210, 161, 31))
            font = QtGui.QFont()
            font.setPointSize(16)
            self.password_label.setFont(font)
            self.password_label.setObjectName("password_label")
            self.password_label_2 = QtWidgets.QLabel(central_widget)
            self.password_label_2.setGeometry(QtCore.QRect(20, 270, 171, 31))
            font = QtGui.QFont()
            font.setPointSize(16)
            self.password_label_2.setFont(font)
            self.password_label_2.setObjectName("password_label_2")
            self.password_input_2 = QtWidgets.QLineEdit(central_widget)
            self.password_input_2.setGeometry(QtCore.QRect(209, 270, 201, 31))
            self.password_input_2.setTabletTracking(False)
            self.password_input_2.setAutoFillBackground(False)
            self.password_input_2.setEchoMode(QtWidgets.QLineEdit.Password)
            self.password_input_2.setClearButtonEnabled(False)
            self.password_input_2.setObjectName("password_input_2")
            self.signup_button = QtWidgets.QPushButton(central_widget)
            self.signup_button.setGeometry(QtCore.QRect(150, 350, 151, 35))
            font = QtGui.QFont()
            font.setPointSize(16)
            self.signup_button.setFont(font)
            self.signup_button.setObjectName("login_button")
            self.label.setText("FileSpace")
            self.username_label.setText("Username")
            self.password_label.setText("Create Password")
            self.password_label_2.setText("Create Password")
            self.signup_button.setText("Create Account")


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.show()
    sys.exit(app.exec_())
