# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'StartScreen.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class MainWindow(object):
    def __init__(self):
        self.create_account_button = None
        self.create_account_label = None
        self.login_button = None
        self.password_input = None
        self.username_input = None
        self.password_label = None
        self.username_label = None
        self.label = None
        self.centralwidget = None

    def setup_ui(self, main_window):
        main_window.setObjectName("MainWindow")
        main_window.resize(460, 600)
        main_window.setMouseTracking(True)
        main_window.setTabletTracking(True)
        self.centralwidget = QtWidgets.QWidget(main_window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(134, 60, 191, 51))
        font = QtGui.QFont()
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setMouseTracking(False)
        self.label.setObjectName("label")
        self.username_label = QtWidgets.QLabel(self.centralwidget)
        self.username_label.setGeometry(QtCore.QRect(50, 180, 101, 23))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.username_label.setFont(font)
        self.username_label.setObjectName("username_label")
        self.password_label = QtWidgets.QLabel(self.centralwidget)
        self.password_label.setGeometry(QtCore.QRect(50, 240, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.password_label.setFont(font)
        self.password_label.setObjectName("password_label")
        self.username_input = QtWidgets.QLineEdit(self.centralwidget)
        self.username_input.setGeometry(QtCore.QRect(180, 180, 230, 31))
        self.username_input.setObjectName("username_input")
        self.password_input = QtWidgets.QLineEdit(self.centralwidget)
        self.password_input.setGeometry(QtCore.QRect(180, 240, 230, 31))
        self.password_input.setTabletTracking(False)
        self.password_input.setAutoFillBackground(False)
        self.password_input.setObjectName("password_input")
        self.login_button = QtWidgets.QPushButton(self.centralwidget)
        self.login_button.setGeometry(QtCore.QRect(180, 300, 100, 35))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.login_button.setFont(font)
        self.login_button.setObjectName("login_button")
        self.create_account_label = QtWidgets.QLabel(self.centralwidget)
        self.create_account_label.setGeometry(QtCore.QRect(50, 350, 171, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_account_label.setFont(font)
        self.create_account_label.setObjectName("create_account_label")
        self.create_account_button = QtWidgets.QPushButton(self.centralwidget)
        self.create_account_button.setGeometry(QtCore.QRect(220, 360, 121, 23))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.create_account_button.setFont(font)
        self.create_account_button.setStyleSheet("color: rgb(0, 0, 255)")
        self.create_account_button.setFlat(True)
        self.create_account_button.setObjectName("create_account_button")
        main_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(main_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 460, 21))
        self.menubar.setObjectName("menubar")
        main_window.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(main_window)
        self.statusbar.setObjectName("statusbar")
        main_window.setStatusBar(self.statusbar)

        self.retranslateUi(main_window)
        QtCore.QMetaObject.connectSlotsByName(main_window)

    def retranslateUi(self, main_window):
        _translate = QtCore.QCoreApplication.translate
        main_window.setWindowTitle(_translate("MainWindow", "FileSpace"))
        self.label.setText(_translate("MainWindow", "FileSpace"))
        self.username_label.setText(_translate("MainWindow", "Username"))
        self.password_label.setText(_translate("MainWindow", "Password"))
        self.login_button.setText(_translate("MainWindow", "Log In"))
        self.create_account_label.setText(_translate("MainWindow", "Don\'t have an account?"))
        self.create_account_button.setText(_translate("MainWindow", "Create account"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    main_win = QtWidgets.QMainWindow()
    ui = MainWindow()
    ui.setup_ui(main_win)
    main_win.show()
    sys.exit(app.exec_())
